server:
  port: '8082'
spring:
  profiles:
    active: qa
---

spring:
  profiles: dev
  datasource:
    username: dcbappUser
    url: jdbc:mysql://localhost:3306/dcbapp_dev
    driverClassName: com.mysql.jdbc.Driver
    password: CasaDaMaeJoana@01
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
welcome:
  message: 'Hello World!!'

---
spring:
  profiles: qa
  datasource:
    username: dcbappUser
    url: jdbc:mysql://localhost:3306/dcbapp_qa
    driverClassName: com.mysql.jdbc.Driver
    password: CasaDaMaeJoana@01
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
welcome:
  message: 'Hello World!!'
management:
    endpoints:
      web:
          exposure:
            include: "*"
            exclude: "env,beans"

---
spring:
  profiles: prod
  datasource:
    username: dcbappUser
    url: jdbc:mysql://localhost:3306/dcbapp
    driverClassName: com.mysql.jdbc.Driver
    password: CasaDaMaeJoana@01
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
welcome:
  message: 'Hello World!!'
